Repository fga-eps-mds/2023.2-UnB-TV-Frontend, pull requests merged in 2023-12, with the labels that each got.

#30 arrumando responsividade da tela
  src/app/pages/participate/participate.component.css
Labels: NOT RELEASE

#33 Major Release
  package.json
  src/app/app.module.ts
  src/app/components/background/background.component.html
  src/app/components/background/background.component.ts
  src/app/components/video-comment/video-comment.component.css
  src/app/components/video-comment/video-comment.component.html
  src/app/pages/grid/grid.component.css
  src/app/pages/grid/grid.component.html
  src/app/pages/participate/participate.component.css
  src/app/pages/participate/participate.component.html
  src/app/pages/profile/profile.component.css
  src/app/pages/profile/profile.component.html
  src/app/pages/profile/profile.component.ts
  src/app/pages/stream-view/stream-view.component.css
  src/app/pages/stream-view/stream-view.component.html
  src/app/pages/stream-view/stream-view.component.spec.ts
  src/app/pages/stream-view/stream-view.component.ts
  src/app/pages/suggest-agenda/suggest-agenda.component.css
  src/app/pages/suggest-agenda/suggest-agenda.component.html
  src/app/services/date.service.spec.ts
  src/app/services/date.service.ts
  src/assets/fonts/UnB Pro_Black.otf
  src/assets/fonts/UnB Pro_Bold Italic.otf
  src/assets/fonts/UnB Pro_Bold.otf
  src/assets/fonts/UnB Pro_Italic.otf
  src/assets/fonts/UnB Pro_Light.otf
  src/assets/fonts/UnB Pro_Regular.otf
  src/shared/model/schedule.model.ts
Labels: MAJOR RELEASE

#38 Teste-active-account
  package-lock.json
  src/app/pages/active-account/active-account.component.spec.ts
  src/app/pages/grid/grid.component.css
  src/app/pages/grid/grid.component.html
  src/app/pages/login-social/login-social.component.css
  src/app/pages/profile/profile.component.html
  src/app/pages/video-viewer/video-viewer.component.html
Labels: DEVELOP

#36 126 mascara
  src/app/pages/suggest-agenda/suggest-agenda.component.css
  src/app/pages/suggest-agenda/suggest-agenda.component.html
  src/app/pages/suggest-agenda/suggest-agenda.component.spec.ts
  src/app/pages/suggest-agenda/suggest-agenda.component.ts
Labels: DEVELOP

#40 Adiciona compartilhamento nos vídeos
  src/app/pages/login-social/login-social.component.css
  src/app/pages/video-viewer/video-viewer.component.html
  src/app/pages/video-viewer/video-viewer.component.spec.ts
  src/app/pages/video-viewer/video-viewer.component.ts
  src/assets/share.png
Labels: DEVELOP

#43 Corrige testes de login social
  src/app/pages/login-social/login-social.component.spec.ts
Labels: FIX RELEASE
