Repository fga-eps-mds/2023.2-UnB-TV-Frontend, pull requests merged in 2023-11, with the labels that each got.

#19 Adiciona scripts sonar
  .github/workflows/continous-integration.yml
  .github/workflows/release.yml
  scripts/consts.js
  scripts/package.json
  scripts/release.js
  sonar-project.properties
Labels: DEVELOP

#16 51 descricao
  src/app/app.module.ts
  src/app/components/background/background.component.html
  src/app/pages/profile/profile.component.spec.ts
  src/app/pages/video-viewer/video-viewer.component.css
  src/app/pages/video-viewer/video-viewer.component.html
  src/app/pages/video-viewer/video-viewer.component.spec.ts
  src/app/pages/video-viewer/video-viewer.component.ts
  src/app/pages/video/video.component.html
  src/app/pipes/safe.pipe.spec.ts
  src/app/pipes/safe.pipe.ts
  src/app/services/video.service.spec.ts
  src/app/services/video.service.ts
  src/shared/model/video.model.ts
Labels: NOT RELEASE

#18 46 footer fix
  src/app/app.module.ts
  src/app/components/background/background.component.html
  src/app/components/background/background.component.spec.ts
  src/app/components/background/background.component.ts
  src/app/pages/agora/agora.component.css
  src/app/pages/agora/agora.component.html
  src/app/pages/agora/agora.component.spec.ts
  src/app/pages/agora/agora.component.ts
  src/app/pages/programacao/programacao.component.css
  src/app/pages/programacao/programacao.component.html
  src/app/pages/programacao/programacao.component.spec.ts
  src/app/pages/programacao/programacao.component.ts
Labels: NOT RELEASE

#23 07 suggest agenda
  src/app/pages/suggest-agenda/suggest-agenda.component.css
  src/app/pages/suggest-agenda/suggest-agenda.component.html
  src/app/pages/suggest-agenda/suggest-agenda.component.spec.ts
  src/app/pages/suggest-agenda/suggest-agenda.component.ts
Labels: NOT RELEASE

#22 47 assistir stream
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/pages/stream-view/stream-view.component.css
  src/app/pages/stream-view/stream-view.component.html
  src/app/pages/stream-view/stream-view.component.spec.ts
  src/app/pages/stream-view/stream-view.component.ts
  src/index.html
Labels: MINOR RELEASE
